name: CD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change image tag
        run: |
          sed -i 's\<p>version:.*\<p>version: ${{ github.ref_name }}</p>\g' my_site/index.html
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_REGISTRY_CRED }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crppudjmh5lksthdg9q4
          CR_REPOSITORY: netology_test_app
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          docker build -t cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: GitOps - Checkout
        uses: actions/checkout@v4
        with:
          repository: marc010/test_app_infrastructure
          ref: 'main'
          token:  ${{ secrets.TOKEN_GITHUB }}

      - name: Change image tag
        run: |
          sed -i 's/tag:.*/tag: ${{ github.ref_name }}/g' helm/values.yaml

      - name: setup git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "cd.github-actions@github.com"
          git add .
          git commit -m "Update values.yaml"
          git push origin main
