name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_REGISTRY_CRED }}

#      - name: Build, tag, and push image to Yandex Cloud Container Registry
#        env:
#          CR_REGISTRY: crppudjmh5lksthdg9q4
#          CR_REPOSITORY: my_test
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          docker build -t cr.yandex/crppudjmh5lksthdg9q4/my_test:${{ github.sha }} .
#          docker push cr.yandex/crppudjmh5lksthdg9q4/my_test:${{ github.sha }}

      - name: Show tag
        run: echo ${{ toJSON(github) }}

#      - name: Check if tag is present
#        id: check_tag
#        run: |
#          if [[ ${{ github.ref }} == 'refs/tags/*' ]]; then echo "${{ github.ref }}"; else echo "NOTAG"; fi

#      - name: Modify values.yaml if tag is present
#        if: ${{ steps.check_tag.outputs.tag != 'NOTAG' }}
#        run: |
#          sed -i 's|old_value|new_value|g' values.yaml
#
#      - name: Commit and push changes to values.yaml
#        if: ${{ steps.check_tag.outputs.tag != 'NOTAG' }}
#        run: |
#          git config --global user.email "github-actions@github.com"
#          git config --global user.name "GitHub Actions"
#          git add values.yaml
#          git commit -m "Update values.yaml"
#          git push