name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_REGISTRY_CRED }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crppudjmh5lksthdg9q4
          CR_REPOSITORY: my_test
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/crppudjmh5lksthdg9q4/my_test:${{ github.sha }} .
          docker push cr.yandex/crppudjmh5lksthdg9q4/my_test:${{ github.sha }}

      - name: Show tag
        run: echo ${{github.ref_name}}