name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

#    env:
#      YC_REGISTRY_CRED: ${{ secrets.YC_REGISTRY_CRED }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Login to Yandex Registry
##        run: echo $YC_REGISTRY_CRED | docker login --username json_key --password-stdin cr.yandex
#        uses: docker/login-action@v3
#        with:
#          registry: cr.yandex
#          username: json_key
#          password: ${{ secrets.YC_REGISTRY_CRED }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: test_app:${{ github.sha }}

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_REGISTRY_CRED }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crppudjmh5lksthdg9q4
          CR_REPOSITORY: my_test
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/crppudjmh5lksthdg9q4/my_test:${{ github.sha }} .
          docker push cr.yandex/crppudjmh5lksthdg9q4/my_test:${{ github.sha }}